### ISSUE TITLE
City boundaries

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#1]
@ZanSara 

Io toglierei la menata dei limiti cittadini.

Mettiamolo nei domain assumption e fine.

Pensi sia importante?

**Comment by ZanSara** [comment]
In verita' ieri mi sono fatta una scampagnata nel forum e, oltre ad averci trovato un po' di cose interessanti, ho visto che i prof molto spesso dicevano di non iper-semplificare il problema e "attenersi alla realtà". In effetti è probabile che qualcuno decida di uscire dalla città in auto, per cui dovremmo considerare anche questo caso, credo...

**Comment by siscia** [comment]
Beh potremmo semplicemente chiedere sul forum.
Penso ne avrebbe parlato...

**Comment by siscia** [comment]
https://beep.metid.polimi.it/web/121843524/forum/-/message_boards/message/124138417?&#p_19

**Comment by ZanSara** [comment]
Ok grazie! Vediamo che dicono

**Comment by siscia** [comment]
Eh Sarina, l'argomento è gia stato trattato molte volte sia in classe che nel forum.

Che cazzo di domande facciamo anche noi???

**Comment by ZanSara** [comment]
Ma certo! Ne ho sentito parlare moltissimo in classe 😓
Ho rispulciato il forum e credo di aver trovato il thread a cui si riferisce:
https://beep.metid.polimi.it/web/121843524/forum/-/message_boards/message/123843739?&#p_19
(btw, in questo thread la risposta della Di Nitto e' assai... criptica)

**Comment by siscia** [comment]
Si l'ho trovato anche io...

Comunque non vorrei dirlo così ma ti sembra ragionevole che uno si debba guardare tutti i thread per trovarlo uno con un nome che non c'entra assolutamente un cazzo "Question to clients on bad users behavior" ? Mah, lasciamo stare...

Sono ancora per togliere questa menata dei limiti cittadini però...
