### ISSUE TITLE
Frasi sospette

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#11]
Ho trovato due frasi sospette negli ultimi paragrafi:

_Merge into a bigger models, make sure that nothing can go wrong with different part **iterating**_
_Verify correctness also of **iteration** between users and cars_

Intendevi davvero **to iterate** o volevi dire **to interact**? Perche' poi due righe sotto torna ad essere:

_User **interacting** with the cars._

**Comment by siscia** [comment]
Si hai ragione correngo
