### ISSUE TITLE
Requirement mancante

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#12]
Manca la possibilita' di cancellare le prenotazioni tra i requirements.

**Comment by siscia** [comment]
@ZanSara ricontrolla per piacere...

Ma è necessario dare questa possibilità all'utente? Cioè, non possiamo semplicemente non parlarne?

**Comment by ZanSara** [comment]
Secondo me se non ne parliamo sembra che le prenotazioni non si possano proprio cancellare, il che mi pare abbastanza stupido.
Le fix vanno benissimo, ma mi sono accorta che bisogna cambiare anche lo State Diagram e le Text Assumptions sugli stati (al momento avevo specificato che da Booked si puo' solo passare a Riding). Dopo dedico 5 minuti a questa cosa.

**Comment by siscia** [comment]
E in teoria l' Alloy... Ora ci penso con calma

**Comment by ZanSara** [comment]
Perfetto
