### ISSUE TITLE
Sblocco automatico dell'auto prenotata

### ISSUE THREAD

**Issue by GianpaoloBranca** [siscia/INGSW2#14]
(sono Sara)
Nel RASD avevamo scritto che quando l'utente si avvicina all'auto che ha prenotato, il sistema sblocca automaticamente la sua auto.
Ma il telefono non manda la sua telemetria. Come lo facciamo funzionare?

**Comment by siscia** [comment]
@ZanSara cambiamo il RASD

**Comment by ZanSara** [comment]
Forse non e' necessario...
Potremmo decidere che il telefono sa le coordinate della sua auto. Quando le coordinate approssimativamente coincidono, chiede al server di sbloccare l'auto.
Credi che possa funzionare?

**Comment by siscia** [comment]
Si chiaro può funzionare, però ci complica la vita in modo eccessivo; a mio parere è semplicemente stata una svista nel RASD. Sistemiamo quello e fine.

**Comment by ZanSara** [comment]
Ok, come correggo? Facciamo in modo che l'utente possa sbloccare la sua auto manualmente quando ci arriva?

**Comment by siscia** [comment]
Si direi di si...

Cioè come funziona Enjoy, quando l'utente clicca "Sblocca" sull app la macchina si apre.

**Comment by ZanSara** [comment]
Ok sistemo il RASD

**Comment by siscia** [comment]
Mi pare buono. Devo riguardare se avevo usato la vicinanza da qualche parte (e forse avevo) e nel caso dire che l'utente deve essere vicino quando sblocca la macchina.

**Comment by siscia** [comment]
Continuiamo su #20
