### ISSUE TITLE
Le multe

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#15]
Avevamo detto che delle multe non ci saremmo occupati, ma nei goals risulta in effetti che le multe arrivano sulla app.
Cambiamo i goals nel RASD e gia' li specifichiamo che le multe sono gestite dalla compagnia senza che a noi interessi come?

**Comment by siscia** [comment]
Si direi di si

**Comment by siscia** [comment]
Stavo cercando di capire se era possibile fare una via di mezzo, che a questo punto dovremmo cancellare completamente la parte relativa al GOAL FINES e fare finta che non esistano multe. E a me andrebbe bene.

@ZanSara Te che ne pensi?

**Comment by ZanSara** [comment]
Si dai possiamo toglierle completamente... Aggiungo magari due righe nella prima sezione dicendo che le multe vengono gestite dall'azienda.

**Comment by ZanSara** [comment]
Anzi potremmo dire questo: "a noi non interessa come le gestite, noi forniamo solo la possibilita' di associare un'auto al conducente che la guidava in quel momento in modo che voi possiate mandare la multa alla persona giusta".
E pensandoci, trovare l'utente che guidava una certa auto in un certo momento potrebbe essere utile anche per lo staff che ripara le auto.
In questo caso riduciamo il goal FINES a un solo requirement, che alla fine e' una query al db e sarebbe riciclabile. Che ne dici?

**Comment by ZanSara** [comment]
Per adesso ho messo nel RASD questa cosa del poter solamente cercare chi guidava l'auto al momento della multa e aggiunto il paragrafetto. Ho anche dovuto modificare lo scenario 3 e lo use case... spero di non essermi persa nulla
