### ISSUE TITLE
bottom_up approach new branch though?

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#16]
@ZanSara 

Sarina, mi dai un occhio a quello che ho messo nel branch bottom_up.

Questo è pù o meno l'approccio che darei io, con più figure e completato meglio, però è come lo farei io.

Che ne dici?

**Comment by ZanSara** [comment]
L'ho letto e a me sembra, oltre che completo e strutturato bene, anche piu' chiaro del suo modello...
Probabilmente ci dira' di mettere piu' diagrammi, specie per l'architettura di alto livello. Considera che il DD di esempio e' quasi unicamente diagrammi (per quanto inutili essi possano essere): dubito che li abbiano messi di loro spontanea volonta' :P.
Se ce lo accetta e' fantastico :) (e mi lancero' nuovamente in un giro di spellchecking perche' ne ho visti diversi alla prima lettura :grin: )

**Comment by ZanSara** [comment]
La Di Nitto approva, hai visto? Direi che possiamo continuare con il tuo modello :)

**Comment by siscia** [comment]
Si ho visto poco fa :)
