### ISSUE TITLE
Goals vs Requirements

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#2]
Sul forum dicono che tra i goals e' sufficiente mettere "PE applica una tariffa all'utente", mentre nei requirements si specificano esattamente sconti e sovrapprezzi. Ti cambio i goals e i requirements per adeguarci a questa cosa?

https://beep.metid.polimi.it/web/121843524/forum/-/message_boards/message/124007783?&#p_19

**Comment by siscia** [comment]
Stavo guardando anche io... Se vuoi fare te vai pure, altrimenti lo sistemo io :)

**Comment by ZanSara** [comment]
Allora faccio io, che gia' sto facendo i requirements :+1:
