### ISSUE TITLE
Locate the user

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#20]
Nella descrizione dell'interfaccia (sez. 2.2), sotto UNLOCK, ho trovato questo:

*\item[POSITION] The system must be able to locate the user.*

Mi pare di aver tolto dal RASD lo sblocco automatico... e' un refuso o ci siamo intesi male? Al momento ho fatto in modo che l'utente mandi sempre il comando di sblocco manualmente, senza che il sistema si occupi di capire se e' arrivato vicino all'auto o no (per quella storia del fatto che il telefono non manda telemetria)

**Comment by ZanSara** [comment]
Idem per POSITION/User sotto la sezione 2.3

**Comment by siscia** [comment]
Per come l'avevo inteso io, l'utente deve premere E essere vicino.

**Comment by ZanSara** [comment]
Mi dai feedback contrastante su questa cosa 😅
https://github.com/siscia/INGSW2/issues/14

**Comment by siscia** [comment]
Ahaha, no chiariamoci, io farei che l'utente deve essere vicino e cliccare il pulsante. Fine.

Non ci piace? Troppo sbatti?

**Comment by ZanSara** [comment]
Piu' che altro io avevo dato quella versione per "definitiva" e avevo gia' tolto ogni riferimento al fatto che l'utente deve essere vicino, quindi da nessuna parte e' specificata questa cosa ormai. 
A questo punto mi sembra piu' facile toglierla che rimetterla, a meno che l'Alloy non ne risenta o ci siano evidenti controindicazioni. E inoltre dovremmo specificare che significa "vicino" e chi decide se l'utente e' vicino (il sistema o linf.io?).

**Comment by siscia** [comment]
vada per togliere allora.

L'Alloy andava cmq riguardato per qualcosa di cui non mi ricordo...

**Comment by ZanSara** [comment]
#12
