### ISSUE TITLE
Requirement mancante N°2

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#21]
In effetti tra i requirements non c'è traccia del fatto che l'utente possa inviare una issue report.
Modifico ancora il RASD per aggiungerlo?

**Comment by siscia** [comment]
Mah, in verità se nel RASD non lo abbiamo messo possiamo semplicemente toglierlo proprio.

Anche se a questo punto chi è che crea le issues? 

Decidi te, o si toglie del tutto o si aggiunge al RASD

**Comment by ZanSara** [comment]
Aggiunto REPORT_ISSUE nel RASD
