### ISSUE TITLE
"Un-fixable issue"

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#22]
Nella sezione 2.3 ho trovato, sotto ISSUE_MANAGER:

*The operator may have fixed the issue, may decide that he is not capable to fix the issues or it may decide that the issues is un-fixable.*

Non avevo mai preso in considerazione la possibilta' di avere issue "non risolvibili". Devo includerlo nei diagrammi o tolgo questa frase?

**Comment by siscia** [comment]
Ah ok, qua intendevo un qualcosa di grosso e quindi la macchina deve essere portata in officina. Mentre per le issue normali pensavo a qualcosa di più piccolo, tipo una ruota bucata o una lampadina fulminata, roba che può essere risolta in mezzo alla strada o in un parcheggio.

**Comment by ZanSara** [comment]
Per quelle cose avevo messo la Mechanical Issue. A meno che l'auto non voglia essere rimossa dalla flotta (ma non abbiamo mai considerato questo caso) prima o poi verra' riparata e nel frattempo avra' una Mechanical Issue come status.
Per ora ho tolto quella possibilita', ma se non ti convince ne parliamo.
