### ISSUE TITLE
Struttura e tecnologie

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#23]
Molto strutturato e ben fatto, grazie @ZanSara Sarina.

L'unico appunto è che avevo messo la scelta delle tecnologie come ultima cosa per una serie di motivi.

1. In effetti non ne hai bisogno, nè in 2.4 nè in 2.5 menzioni mai client server o PubSub
2. Il proff vuole che il design non sia guidato dalla tecnologia che scegliamo ma che al contrario la tecnologia sia scelta sulla base del design, se mettiamo prima le tecnologie ho paura che questo punto possa non trasparire bene.

Sarei quindi per spostare la scelta delle tecnologie più in basso.

**Comment by ZanSara** [comment]
Hmmm hai ragione. In effetti pensavo che la scelta del protocollo di comunicazione fosse piu' una scelta di design che una vera e propria tecnologia adottata, ma probabilmente hai ragione tu.
Varrebbe la pena di mettere una domanda sul forum per questo... ora vedo se mi riesce di scriverla.

**Comment by siscia** [comment]
No aspetta, ti dico questo perchè nel forum lo ha già scritto lui...

**Comment by siscia** [comment]
https://beep.metid.polimi.it/web/121843524/forum/-/message_boards/message/125533516?&#p_19

**Comment by ZanSara** [comment]
Ok me l'ero perso
