### ISSUE TITLE
Dividere UI utenti da UI staff

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#25]
Siccome nel diagramma li hai divisi (btw, che genere di diagramma è? Non so come descriverlo) potrebbe essere interessante dividerli anche nella sezione 2.2. Tanto è chiaro già nei Goals cosa è riferito ai customer e cosa allo staff

**Comment by siscia** [comment]
Non ha un nome come diagramma, ero solo per dare una visualizzazione all'idea.

Si può avere un senso dividerli ma va fatto con attenzione.

Andrebbe spiegato che in effetti roba come il Login è presente anche nell'app dello staff (corretto?) e che non la mostriamo perchè in effetti è di secondaria importanza rispetto al resto.

**Comment by ZanSara** [comment]
Allora potremmo gerarchizzare: 

UI/Login per tutti, 
UI/Cust/Book per gli utenti, 
UI/Staff/FindIssue per lo staff. 

Che ne dici? Ovviamente poi lo spieghiamo.

**Comment by ZanSara** [comment]
Procedo anche con questo?

**Comment by siscia** [comment]
Si mi pare un ottima idea.

Occhio che non è più UI ma SB

**Comment by siscia** [comment]
:+1:
