### ISSUE TITLE
Diagramma UI

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#26]

**Comment by ZanSara** [comment]
Vorrei metterlo sotto o sopra la sezione 2.2, ma secondo me manca una cosa: oltre a listare i goals, sarebbe piu' "informativo" tracciare una bella freccia da ognuno di essi verso l'elemento di un altro blocco, ``Sy``, che contiene tutti gli elementi necessari che abbiamo identificato nel backend.

**Comment by siscia** [comment]
Si chiaro aggiungerebbe informazione, mi piacerebbe farlo ma visto il poco tempo non l'ho fatto... Lo terrei come bassa priorità comunque.

**Comment by ZanSara** [comment]
:+1: lascio aperto allora

**Comment by ZanSara** [comment]
https://github.com/siscia/INGSW2/commit/d38f5865f7ce3e3684cac98963b4ac72d347af62

**Comment by siscia** [comment]
Mi piace un sacco, l'unica cose è che forse serve una freccia in più da SafeAreas di User a GeoLocationAreas ?

**Comment by ZanSara** [comment]
Guardo subito

**Comment by siscia** [comment]
:+1:
