### ISSUE TITLE
Multa per prenotazione scaduta

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#28]
Chi e' il responsabile di far pagare all'utente le multe per prenotazione scaduta? Secondo il DD sarebbe BOOKING, ma mi torna molto male.

_BOOKING/Expire ⇔ Sy/BookExpire
Responsability: Removes an expired reservation and fines the related user._

Perche' Booking e' responsabile di un pagamento? Non dovrebbe stare sotto BILLING? E allora e' meglio fare una funzionalita' a parte oppure conviene *riciclare* questa:

_BILL/Calculate ⇔ Sy/CalculatFee
Responsability Calculates the amount of a riding fee.
Input The ID of the ride.
Output The final fee, including eventual discounts or overprices._

?

**Comment by ZanSara** [comment]
Allora considero che Book/Expire usa BILL/CalculateFee per creare la multa.

Solo un dettaglio: per come l'avevi pensato, CalculateFee chiama per conto suo SendFee e MakePayment (cioe' completa il pagamento) o chiamare queste due e' responsabilita' del chiamante?

**Comment by siscia** [comment]
Allora, facciamo così.

Creiamo dei componenti che dato l'ID di un Ride calcolano il dovuto per il ride finito, oppure calcolano il dovuto per un booking expired oppure il dovuto per un unsafe parking e creano un oggetto fee.

L'oggetto fee viene quindi passato a BILL/Pay che chiede all'utente di pagare.

**Comment by ZanSara** [comment]
Ok!

**Comment by ZanSara** [comment]
Ops non volevo chiuderla 😅 La chiudo quando lo abbiamo fatto
