### ISSUE TITLE
Responsabilita' di NOTIFIER

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#29]
A prescindere dal discorso di prima, NOTIFIER continua a turbarmi.
Come responsabilita' mi sembra troppo vaga: ci sono altri componenti che "notificano" le loro cose all'utente in piena autonomia senza ricorrere ad esso: per esempio **BOOKING/Expire**

_(a meno che io non abbia frainteso e tu intenda dire che Booking/Expire viene invocata dalla app: allora ti direi che secondo me e' una vulnerabilita' difficile da gestire ma sarebbe un'altra discussione)_

Di conseguenza, non conviene smembrare NOTIFIER e assegnare le sue funzioni ad altri componenti?
Suggerirei:
 - BILLING/SendFee
 - RIDE/UnsafeParkingNotification (ora che ci penso, anche CAR/Ride mi sembra che ci stia meglio sotto RIDE)
 - RIDE/CarPluggedNotification

**Comment by ZanSara** [comment]
Allora NOTIFIER potrebbe essere ridotto a una sola funzione *Notify* che prende una notifica e la invia al client... per ora lo utilizzo cosi nel sequence, poi correggiamo il DD se sei d'accordo.

**Comment by siscia** [comment]
Si certo, può essere ridotto ad un solo componente, sono tutte scelte di design.

In questo modo è più corposo ed ogni cosa è ben definità, come hai proposto te è più flessibile. Niente di male con nessuno dei due.

**Comment by siscia** [comment]
Aspetta, finiamo questo discorso.

Non avevo pensato che altre funzionalità potessero fare una notifica all'utente. Cose tipo BOOK/Expire mi imaginavo che l'utente se ne era fregato e quindi pace li mandiamo la multa e affari suoi.

Se vogliamo notificare, servono altre NOTIFY/Stuff, oppure facciamo un semplice NOTIFY/Notify.

La motivazione l'ho scritta qua: https://github.com/siscia/INGSW2/compare/explaination#diff-643ec3ee359fbd3a00eaf3ee67020556R643

**Comment by ZanSara** [comment]
La motivazione mi sembra molto chiara.
Da parte mia propendo per il NOTIFY/Notify, in modo che se domani voglio spammare di notifiche l'utente (per l'appunto) non devo reimplementare cento diverse notifiche.

**Comment by siscia** [comment]
Ahaha, scegli te :) 

Sai le mie motivazioni, ma avendo scritto io il documento mi pare giusto che sei te a confermarlo oppure no.

Mettiamo un solo NOTIFY/Notify ?

**Comment by ZanSara** [comment]
Approvato il NOTIFY/Notify :+1:

**Comment by siscia** [comment]
@ZanSara chiudi te se tutto corretto.
