### ISSUE TITLE
Posizione delle auto in status "Available" e "Booked"

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#3]
Facendo i reqs mi e' venuto in mente un dettaglio:
_Le auto che hanno status "Available" o "Booked" non cambiano la loro posizione_ (e cose simili per gli altri status delle auto)
Questo e' un domain assumption? Un text assumption? Non so dove metterlo 😅

**Comment by ZanSara** [comment]
Idem per cose tipo _un'auto "Available" o "Booked" non cambia la sua carica residua_, _un'auto "Booked" non cambia proprietario senza passare da "Available"_ etc

**Comment by siscia** [comment]
Ehhh, boh... Mi sembrano domain assumption, nel dominio della realtà una macchina non si muove da sola, così come una batteria non si scarica da sola (entro certi range).

Anche se magari un auto appena lasciata fuori da una safe zone deve essere spostata...

**Comment by ZanSara** [comment]
Quest'ultima cosa posso provare a specificarla.
Mentre cose del tipo
_un'auto "Booked" non cambia proprietario senza passare da "Available"_
_un'auto Booked e' associata a una sola persona_
etc... sono text assumptions, secondo te?

**Comment by siscia** [comment]
Ma il confine è labile...

Direi che sono text assumption, ma è chiaro che a noi appaiono tali perchè abbiamo già l'idea del dominio in cui queste cose dovrebbero operare.

Mettiamo text assumption

**Comment by ZanSara** [comment]
Ok :+1:
