### ISSUE TITLE
Query sullo stato delle auto

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#30]
Quando un utente vuole avere ulteriori dettagli sull'auto che sta per prenotare (banalmente, per sapere quant'e' la sua carica residua) quale componente contatta?
CAR non espone un sistema di ricerca, e non penso che la query a linf.io che ho fatto per avere la lista delle auto vicine mi abbia fornito questo dato.
Potremmo assegnarlo a POSITION e aumentargli le responsabilita' in "fornisce i dettagli dell'elemento di interesse specificato (inclusa la sua posizione attuale)"

**Comment by siscia** [comment]
immaginavo che GEOLOCATION/AvailableCar ritorna tutte le informazioni della macchina necessarie.

**Comment by ZanSara** [comment]
Puo' funzionare solo se sto cercando le auto disponibili pero'. Nel caso in cui io voglio vedere i dettagli dell'auto che ho prenotato, la app non sa a chi fare la query per sapere i dati che le interessano: a meno che anche POSITION non ritorni tutti i dati necessari, ma allora aumentano le responsabilita'.

**Comment by siscia** [comment]
Si, hai ragione... Immagino che l'app se lo tenga in memoria... 

Vogliamo modellare anche questa cosa o lo consideriamo un dettaglio?

**Comment by ZanSara** [comment]
bella domanda... Potresti semplicemente aggiungere una funzioncina sotto CARS se non e' troppo sbatti, cosi togliamo ogni dubbio. Se no ignoriamolo :)
