### ISSUE TITLE
Car Backend

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#33]
Ne abbiamo parlato pochissimo. Secondo te e' necessario dire che esiste un componente, che non e' la CarGUI, che si interfaccia con i sensori della macchina? (lo scanner, il GPS, etc.)
Preferirei tenere tutte le GUI separate dal resto.

**Comment by siscia** [comment]
Con tutti i sensori della macchina si interfaccia CAR_MANAGER...

Ti torna?

**Comment by ZanSara** [comment]
Non e' un po' fuori dalle responsabilita'? Dopotutto Car_Manager dice: _Responsability: Manages the i*N*teractions between users and cars._

**Comment by ZanSara** [comment]
No ok, anche nel sequence in effetti si puo' togliere.
Mi domando allora se serva una funzione CAR/UnlockEngine() da chiamare solo se la patente e' valida. Che ne dici?

**Comment by siscia** [comment]
Si, hai ragione che a stare precisi sui termini è un attimo fuori dalle sue repsonsabilità.

Ma è propria sbagliata la responsabilità che gli ho dato, la macchina abbiamo detto che non iteragisce dirattamente con l'utente ma solo con il sistema, quindi dovrei cambiare in _Manages the iNteractions between **the system** and cars._

A questo punto la domanda è, cosa è una interazione? Il sistema che vuole sapere la carica di batteria della macchina è una interazione? A mio parere sì, ma sono scelte.

Nota l'esempio che ho scelto, nella realta non sarà il sistema a voler sapere il livello di batteria della macchina ma sarà la macchina che glielo dice senza che gli sia chiesto niente (PubSub), ma, al licello di astrazione su cui lavoriamo a noi di questa distinzione non ci importa.

**Comment by siscia** [comment]
Quello che dici te era dentro CAR/ValidateLicense, si può riscrivere per rendere meglio l'idea di qualcosa che permette di far partire il motore.

**Comment by siscia** [comment]
Vado a prendere la :pizza:

**Comment by ZanSara** [comment]
Ok a posto. Ultimo dettaglio: in effetti, la macchina ha una GUI. Lasciato cosi, sembra che la GUI possa interagire in qualche modo con l'utente.
Per prevenire qualunque dubbio dovremmo specificare che non solo vietiamo ogni interazione app-macchina, ma anche ogni interazione utente-CarGUI: la GUI e' utile solamente per mostrare all'utente messaggi in arrivo dal server, *non* per fare richieste.

**Comment by siscia** [comment]
Lo possiamo dire, ma mi pare un dettaglio abbastanza piccolo...

**Comment by ZanSara** [comment]
Nel dubbio, meglio metterlo che dimenticarlo 😊

**Comment by siscia** [comment]
:+1:

**Comment by siscia** [comment]
:+1:
