### ISSUE TITLE
Funzione che mi dice se ho parcheggiato in una safe area

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#34]
C'e' al momento?

**Comment by siscia** [comment]
Huuum, intendi all'utente tipo notifica che ti dice, "si tutto ok puoi lasciare la macchina qua" o al sistema che data la posizione della macchina ti dice se è all'interno di una safe area?

In entrambi i casi non c'è...

Direi che a noi interessa quella del sistema, e a questo punto la aggiungerei come GEOLOCATION/IsSafeArea magari il componente non è quello più adatto (forse ne servirebbe uno ad hoc) ma è quello che ha i dati sotto mano, quindi ci può stare.

**Comment by ZanSara** [comment]
Intendevo proprio quella del sistema, per capire se l'auto e' stata parcheggiata come si deve quando il conducente esce.
Forse e' piu' appropriato sotto POSITION, visto che prende in input l'ID auto?
NB ricordati di togliere Position/User

**Comment by siscia** [comment]
Ah, io pensavo di passargli in input le coordinate attuali, in questo modo sei più decoupled. Se un domani abbaimo i motorini, o vogliamo vedere se una persona è all'iterno di un parcheggio per prendere la sua macchina...

Comunque... Lo avrei messo sotto GEOLOCATION per il tipo di query che è, ci sono database (o estensioni di db) apposta per maneggiare questo tipi di dati, anche se, in effetti è una considerazione che non avrei dovuto ancora fare. http://postgis.net/

Anche sotto POSITION va bene, soprattuto se prende l'ID della macchina.

Scegli te.

**Comment by ZanSara** [comment]
Hai ragione... si mi piace di piu' come dici tu. Vada per Geolocation allora :)
(meno male, cosi posso ridurre un filino l'enormita' di questo sequence)
