### ISSUE TITLE
Diagramma "Deploy"

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#35]
Nel diagramma Deploy ho visto che hai messo lo User_Manager a cavallo tra app e server.
Come mai? Quale funzionalita' di User_Manager sta sulla app? Potrei dover correggere il sequence LoginReg, fammi sapere.

**Comment by siscia** [comment]
Nel RASD parlavamo che l'utente deve accettare delle condizioni d'uso per registrarsi. Questa è la principale, e abbastanza debole, motivazione per cui l'ho messo a cavallo dei due.

**Comment by ZanSara** [comment]
Ah urca... potremmo anche dire che se ne occupa la GUI: un link alle Terms&Conditions e una spunta "Ho letto questa roba". 
Altrimenti nella sezione del deploy devi dire quali funzioni stanno sulla app.

**Comment by siscia** [comment]
Se ti torna meglio diciamo tranquillamente che se ne occupa la gui

**Comment by ZanSara** [comment]
Si' mi sembra piu' ragionevole. E' un componente in meno da spezzare, io lo lascerei tutto sul server.
