### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#37]
Mi sembra una svista banalissima... ci siamo dimenticati la possibilita' di fare il logout oppure ci sono delle ragioni valide per cui l'abbiamo tolta?

**Comment by siscia** [comment]
Mai considerata, ma tipo nemmeno nel RASD.

Che facciamo? Lo mettiamo dentro dall'RASD? Lo aggiungiamo come funzionalità all USER_MANAGER?

**Comment by ZanSara** [comment]
Secondo me se la aggiungiamo solo in User_Manager non se ne accorge nessuno. E se ci fanno un appunto diremo "il goal Login ovviamente includeva anche il logout."

**Comment by siscia** [comment]
Ottimo

**Comment by siscia** [comment]
@ZanSara chiudi te per piacere
