### ISSUE TITLE
POSITION/User va tolto?

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#38]
Mi hai chiesto di togliere POSITION/User, corretto?

Non ci serve?

**Comment by ZanSara** [comment]
Sisi togliamolo

**Comment by siscia** [comment]
Quindi un utente sblocca la macchina dovunque lui sia, corretto ? Il RASD è coerente?

**Comment by ZanSara** [comment]
Si l'avevo rivisto appositamente per questo. Magari gli do un'occhiata all'ultimo ma sono abbastanza certa.
L'unico che non ho controllato e' l'Alloy.

**Comment by siscia** [comment]
Allora nell'Alloy ho proprio una asserzione `UnlockedCarHasIsUserNearby` quindi in tutto l'Alloy ho considerato che un utente che sblocca la macchina è vicino alla macchina stessa.

Cosa facciamo? Dal tuo punto di vista quanto è sbatti fare in modo che l'utente deve essere vicino alla macchina per sbloccarla?

**Comment by ZanSara** [comment]
Bisogna almeno rivedere il RASD... comincio da quello. Per il resto non dovrebbe esserci quasi nulla da correggere nel DD, eccetto forse qualche pezzettino di sequence.

**Comment by ZanSara** [comment]
Allora. Ho controllato i sequence e:
 - se l'utente puo' tentare lo sblocco manuale in qualsiasi momento e il sistema lo impedisce se e' lontano, il sequence non va modificato
 - se l'utente puo' vedere il bottone solo quando e' vicino all'auto, devo fare una piccola modifica.

Propendo per la prima scelta, tanto la differenza mi pare piccola.
(ora faccio una scampagnata nel RASD a sistemarlo e poi ti aggiorno)

**Comment by siscia** [comment]
:+1:
