### ISSUE TITLE
Cambiare UI in qualcosa di più meglio assai. 

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#39]
Seguendo la discussione #24 avevi proposto di cabiare UI in qualcosa tipo SystemBoundaries o anche solo Boundaries.

Ancora corretto ? Vado avanti?

**Comment by ZanSara** [comment]
Sto facendo io ora!

**Comment by ZanSara** [comment]
Chiudilo tu quando lo hai visto :)
