### ISSUE TITLE
Auto sbloccata e non utilizzata

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#4]
Ho trovato un altro caso speciale in cui non so come sarebbe meglio comportarsi:
_If a user unlocks the car and does not enter it in a short period of time (namely 5 minutes) the car gets back to Booked and the timer restarts._
(Nota: l'auto viene sbloccata automaticamente quando il sistema vede che la posizione dell'utente e quella dell'auto coincidono, ovvero assai meno di 5 min a piedi)
Ti pare un comportamento sensato? Cosa facciamo se un utente raggiunge la sua auto, la sblocca e poi se ne va?

**Comment by siscia** [comment]
Si mi pare un ottima idea

**Comment by siscia** [comment]
Ecco, chiaramente il discorso dei timeout #7 si applica anche qua...
