### ISSUE TITLE
Sy/PositionUser

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#42]
Noi lo abbiamo reinserito, ma occhio che sta sul telefono e non sul server.
Bisogna sistemare la sezione sul deploy e il tuo diagramma.
Confermi?

**Comment by siscia** [comment]
Ehhh si a questo punto si... Riverto il disegnino del deploy.

**Comment by siscia** [comment]
Scusa, il componente position non è di gia a cavallo tra tutti e tre?

**Comment by ZanSara** [comment]
😅 hai ragione mi sono confusa con Geolocation
