### ISSUE TITLE
Rivedere il ComponentsDiagram

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#43]
Va aggiornato con le nuove funzioni.
Lo sto sistemando io

**Comment by siscia** [comment]
Ok grazie

**Comment by ZanSara** [comment]
Ho pushato l'InterfaceDiagram (https://github.com/siscia/INGSW2/commit/56c6db2e8a0230f903308f407f12d48ae3544331)
Resta da fare solo il ComponentsDiagram

**Comment by siscia** [comment]
Come siamo messi qua?

**Comment by siscia** [comment]
Avessi capito cos'è questo ComponentsDiagram lo farei volentieri io...

**Comment by ZanSara** [comment]
Guarda l'ho quasi completato :) Dopo pranzo lo pusho
