### ISSUE TITLE
Capitolo 2.8, serve?

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#44]
Ci serve il capitolo 2.8 ?

Mi pare che sia rimasto dalle vecchie revisioni, confermi?

E il 2.7? Si, direi che il 2.7 ha un ruolo più specifico e necessario.

**Comment by ZanSara** [comment]
secondo me da 2.4 al 2.5 bisogna rivedere un attimo la struttura... il 2.8 invece era quello del deploy, ne hai parlato altrove? Secondo me anche quello andrebbe messo dalle parti del tuo diagramma Deploy, invece che cosi lontano.

**Comment by siscia** [comment]
Si serve decisamente, e hai ragione su un restructuring.
