### ISSUE TITLE
Algo

### ISSUE THREAD

**Issue by siscia** [siscia/INGSW2#45]
Implementazione di alcuni algoritmi critici.

Moh ci devo pensare.

**Comment by siscia** [comment]
Ho implementato un primissimo BookManager, dici basta?

**Comment by ZanSara** [comment]
Per ora e' sufficiente direi. Se poi avanza tempo potremmo magari aggiungere qualcosina, ma bisogna capire cosa.
Ma perche' renderizza cosi' male nel pdf?

**Comment by siscia** [comment]
Non ne ho idea del perchè renderizza così male...

Si ho fatto fatica ad identificare questo come il pezzo di codice più difficile...
