### ISSUE TITLE
Separare lo User_Manager dello Staff da quello dei clienti

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#46]
In modo che non ci sia bisogno di passare, per ogni operazione, se l'utente e' un membro dello staff o no, e per prevenire allo staff di usare il setPaymentInfo.
E' un dettaglio o ne vale la pena?

**Comment by siscia** [comment]
Ma non passare per ogni operazione se è membro dello staff o no, immagino che passi l'ID, dato l'ID sappiamo noi se è parte dello staff oppure no...

**Comment by ZanSara** [comment]
Hm, ok. ma alla registrazione devo specificarlo, almeno.

**Comment by siscia** [comment]
Mah, io immagino che la registrazione sia solo per gli utenti... Per me si può considerare che lo staff venga registrato dalle risorse umane nel sistema, cosa che assolutamente non ci interessa modellare...

Sbaglio?

**Comment by ZanSara** [comment]
ok, ci puo' stare.
