### ISSUE TITLE
Chi chiama Booking/Expire?

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#47]
Prende in input la prenotazione, quindi qualcuno lo sta chiamando...?

**Comment by siscia** [comment]
Ci interessa ? 

Negli algoritmi sto proprio implementando la funzionalità di Booking, quello che ho fatto è un thread che si guarda il primo che scade e se è scaduto inizia la procedura di multa.

**Comment by ZanSara** [comment]
Quindi non prende nulla in input? Era soprattutto questo che mi disturbava, ma visto che nell'implementazione non c'e' input semplicemente tolgo gli argomenti

**Comment by siscia** [comment]
No aspetta, nell'implementazione si che c'è input, si prende in input tutta la lista delle prenotazioni.

Lascia stare che come input è nascosto all'interno degli atrributi privati della classe.

Lascia anche stare che l'implementazione è "furba" ed evita di fare il check per l'expire per ogni singolo elemento, ma se li mette in ordine...

**Comment by ZanSara** [comment]
Ah si hai ragione 😅 Ok sistemo allora
