### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#48]
Sto definendo le interfacce per fare il Components Interfaces Diagram, e naturalmente tante funzioni restituiscono degli oggetti (o quando meno delle strutture dati): tipo GeoLocation restituisce liste di auto/aree/issues.
Dobbiamo considerare anche questi oggetti? Dobbiamo descriverli da qualche parte? Anche se non hanno metodi forse conviene definirli, quando meno per capire cosa restituiscono le varie funzioni.

**Comment by siscia** [comment]
Mah secondo me iniziamo ad esagerare... Ci deve essere un momento in cui ci fermiamo... E descrivere le strutture dati implementative mi pare eccessivo.

**Comment by ZanSara** [comment]
:+1:
