### ISSUE TITLE
Informazioni sulla destinazione

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#5]
Secondo te l'utente deve inserire la sua destinazione quando parte/prenota? Non mi pare necessarissimo, ma in effetti con informazioni sulla destinazione puoi:
- escludere le auto troppo scariche per arrivarci
- mostrare la tariffa approssimativa
- indicare all'utente dove parcheggiare

Inoltre se non vengono date info sulla destinazione, come fa il sistema a dire all'utente quali sono le safe areas vicine alla sua destinazione dove puo' parcheggiare? Gliele mostra tutte man mano che ci passa vicino?

**Comment by siscia** [comment]
Inizia ad essere un attimo complicato secondo me...

Alla fine con Enjoy normale non è richiesto... Non me ne preoccuperei.

**Comment by ZanSara** [comment]
Ok!
