### ISSUE TITLE
ValidateLicence

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#50]
Tu hai scritto che CAR/ValidateLicense() prende in input BookingID.
Questo temo sia impossibile, visto che ValidateLicense viene chiamato dalla macchina, e la macchina in se' non ha idea di chi la abbia prenotata.
Che ne dici?

**Comment by ZanSara** [comment]
idem per lock() : non dovrebbe prendere id della macchina e id dell'utente che vuole bloccarla?

**Comment by siscia** [comment]
Aspetta, ValidateLicense ha bisogno di leggere l'immagine della patente e poi deve anche sapere quale è l'utente.

Quindi l'utente mette la patente sotto lo scan, la macchina scanna l'immagine e la manda al server, il server trova il numero della patente e chi ha prenotato quella machina, combina le due e se le cose corrispondono manda alla macchina il segnale di EngineOn

Si Lock() dovrebbe prendere anche l'ID dell'utente

**Comment by ZanSara** [comment]
Ok quindi confermi che CAR/ValidateLicence prende in input solo l'immagine? Poi ci pensa lei a capire chi ha prenotato quella macchina e se la patente corrisponde.

**Comment by siscia** [comment]
Si e No, il sistema da parte dell'utente prende solo la patente. Overall la funzionalità ha bisogno anche dei dati dell'utente che ha fatto la prenotazione.

**Comment by ZanSara** [comment]
Ok, questo posso specificarlo nell'altro diagramma. Cosi dovrebbe esserci tutto
