### ISSUE TITLE
CAR/Telemetry vs CAR/GetDetails

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#51]
c'e' differenza concettuale, o posso rimuovere CAR/GetDetails?

**Comment by siscia** [comment]
CAR/Telemetry sono i dati che servono a noi, proprio grezzi grezzi, tipo il numero di persone in macchina oppure la carica della batteria.

CAR/GetDetails sono dettagli sulla macchina che mostriamo agli utenti.

Io le lascierei entrambi.

**Comment by ZanSara** [comment]
:+1:
