### ISSUE TITLE
Interfaccia "generale" per customer e staff

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#57]
Mi e' stato suggerito (per motivi di scalabilita') di creare delle interfacce "globali", riservate a customer e staff, che espongono tutti i metodi a loro necessari e fanno da "dispatcher" delle richieste al componente giusto.

Non so quanto questa cosa abbia senso. Tu che ne pensi?

**Comment by siscia** [comment]
Penso che voglio toccare il meno possibile del documento. 

Che la scalabilità non è un concern in alcun modo e che comunque non ho capito come delle interfacce globali possano rendere qualcosa più scalabile (per una qualsiasi definizione di scalabile).
