### ISSUE TITLE
Ristrutturazione del documento

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#58]
Mergio le sezioni 2.4, 2.5, 2.6, 2.7, 2.8, 2.9 (insomma tutto quello che viene prima dei sequence).

Non cancello praticamente niente, riordino solo le cose e rimuovo i pezzi duplicati.

**Comment by ZanSara** [comment]
Dagli un'occhiata e dimmi se va tutto bene

**Comment by siscia** [comment]
Molto bene, lineare e semplice. Ottimo così.
