### ISSUE TITLE
Stub della macchina

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#62]
_[...] we cannot have a car to run physically all the integration tests._

Non e' detto che sia necessaria proprio la macchina... si puo' comunque eseguire i test sul dispositivo della macchina e simulare solo il suo input.

Per come l'hai scritta, sembra che l'intero dispositivo della macchina sia da trasformare in uno stub. Intendevi quello che ho scritto sopra (simulare l'hardware = simulare il motore) o intendevi proprio il dispositivo (simulare l'hardware = simulare il computer di bordo della macchina) ?

**Comment by siscia** [comment]
Qua intendevo che comunque sia tutte le iterazioni Macchina <-> Sistema avvengono comunque via internet, a questo punto ci evitiamo tutto il comparto hardware e facciamo solo un semplice softwarino con le stesse interfaccie della macchina...

Questo è quello che intendevo.

**Comment by ZanSara** [comment]
Cioe' intendevi di non testarlo sulla macchina ma emulare l'hardware, ho capito bene?

**Comment by siscia** [comment]
Si esatto

**Comment by ZanSara** [comment]
ok! Provo a renderlo un po' piu' esplicito allora, poi dimmi se va bene

**Comment by ZanSara** [comment]
Credo che quella parte non vada nella sezione degli stub, ma in una sezione a parte. Ne creo una nuova e lascio stubs vuota per adesso

**Comment by ZanSara** [comment]
Pushato, dimmi che ne pensi

**Comment by siscia** [comment]
Si mi pare molto bene :)
