### ISSUE TITLE
Stub per i servizi esterni

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#63]
Secondo me sarebbe ragionevole usare degli stub anche per i test di integrazione dei servizi esterni. Per esempio i pagamenti andrebbero integrati usando uno stub di stripe, altrimenti come esegui i test?

**Comment by siscia** [comment]
Ehhh, questa è una cosa che mi lascia un pò dubbioso.

Sono necessari test di integrazione con i componenti esterni? La risposta non è semplicemente sì, perchè quello che noi chiamiamo test di integrazione potrebbe tranquillamente essere un unit test dei componenti che si interfacciano con questi servizi esterni.

Gli stub sono molto più utili quando sei te che implementerai quello che deve andare al posto dello stub.

Crearsi uno stub su quello che secondo noi è servizio esterno ha il senso che ha, se poi il servizio non si comporta come lo stub non solo abbiamo perso tempo a fare lo stub ma abbiamo anche dei componenti che non si integrano...

**Comment by ZanSara** [comment]
hmmm... anche questo e' vero. L'utilita' di sicuro e' discutibile. E' anche vero pero' che in qualche modo bisogna assicurarsi che funzionino... 

Cioe', anche se fossero gli unit test dei componenti e non i test di integrazione, il problema si pone lo stesso: non posso verificare se il mio software si interfaccia correttamente a stripe per effettuare un pagamento finche' non eseguo un pagamento. Ma a che pro effettuare pagamenti a caso?

Una cosa del genere onestamente non saprei come gestirla. Sai se nel forum qualcuno ha gia' chiesto una cosa simile? Oppure ignoriamo la questione dicendo che riguarda solo gli unit test e in questa sede non ci riguarda?

**Comment by siscia** [comment]
in verità, servizi tipo stripe hanno loro delle api di "test".

Se semplicemente diciamo che nei nostri unit test usiamo le API di test dei vari servizi?

**Comment by ZanSara** [comment]
Ah certo! Si, direi che questo e' il modo. Semplicemente non lo sapevo 😁
