### ISSUE TITLE
Imporre gli unit test dei componenti come entry criteria

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#64]
Mi sembra decisamente ragionevole, anche se non obbligatorio. Che ne dici?

**Comment by siscia** [comment]
Si chiaro lo possiamo scrivere.

Di filosofia sono abbastanza contrario agli unit test, ma vedo che piacciono quindi mettiamolo pure.

**Comment by ZanSara** [comment]
Davvero? In effetti credo che tutti lo mettano solo per far vedere che sanno cosa sia un unit test. Volendo perdere del tempo possiamo spiegare perche' non li vogliamo... ma per curiosita', perche'?

**Comment by siscia** [comment]
Ehhh ci sono mille motivi, sia filosofici che pratici.

Per prima cosa bisogna distinguere tra unit test e TDD.

TDD (Test Driven Development) suggerisce di scrivere prima i test e poi l'implementazioni, così una volta che hai finito il lavoro sei sicuro che sia già testato.

In generale trovo che gli unit test rallentino abbastanza lo sviluppo e che spesso immobilizzano il design della applicazione => non riscrivo tutto in modo migliore perchè altrimenti dovrei anche riscrivere 100k test cases.

Poi c'è sempre il razionale che se mi metto a testare qualcosa è difficile che io ci trovi un bug dentro. Se scrivo un test per la somma di due numeri, metterò nei test i casi che a me vengono in mente e che quindi sono gia coperti nella implementazione.

Una volta che le API del prodotto sono pensate e ben definite, sono abbastanza pro a scrivere test che verifichino il corretto funzionamento, così che è possibile modificare il code base senza troppe difficoltà e con sicurezza. Ma è un lavoro da fare dopo...

Poi sono favorevole a scrivere i test per debugging.
Vedo un problema che non mi spiego.
Testo le assunzioni che ho una ad una scrivendo unit test.

In questo modo i test rimangono e le parti più "critiche" del codebase sono più coperte.

Poi chiaro che sono filosofie e dipende da milioni di fattori, banalmente a booking.com praticamente non hanno test per quello che succede sul front end, però hanno un sacco di metriche e sistemi automatici (o manuali e molto veloci) di rollback.
Pushano un qualcosa che non funziona bene in produzione, vedono subito che c'è qualche problema, rollback alla versione precedente, analizzano il problema e capiscono cosa è andato storto, mentre in produzione c'è la roba vecchia che funziona.

**Comment by siscia** [comment]
@ZanSara me lo sono autoassegnato, ma se vuoi fare te che hai gia i file aperti fai pure eh... io ci metto ancora un pò...

**Comment by ZanSara** [comment]
Hmm ma quindi lo metto "con riserva" (specificando che vanno fatti alla fine e per debug)? Cioe' quel che dici ha molto senso, in effetti se penso ai pochi casi in cui ho scritto test per il mio software in genere li ho sempre scritti alla fine, dopo aver scritto tutto o quasi 😅

**Comment by siscia** [comment]
La verità è che semplicemente vanno usati con inteligenza e che ci vuole un attimo di esperienza per riuscire a capire cosa è meglio fare...

Però se si scrive una cosa del genere non penso che il proff apprezzi troppo...

Allora, mettiamo come "Entry Criteria" buona confidenza che il componente funzioni da solo in isolamento, confidenza che, per componenti complessi, può richiedere l'uso di unit test.

Che dici?

**Comment by ZanSara** [comment]
Si ci sta :)

**Comment by ZanSara** [comment]
Ah ma era gia' quasi scritto... aggiungo solo una cosina.

**Comment by siscia** [comment]
Ahahah eh beh... XD

**Comment by siscia** [comment]
:+1:
