### ISSUE TITLE
Struttura dei Test Case

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#67]
Credo che andrebbe dettagliata un po' di piu'. Io avrei fatto piu' simile all'esempio, ovvero (esempio):

Test Case ID: IT01C2
Test Items: CAR_MANAGER -> RIDE_MANAGER
Input: The driver exit's signal
Output: A ride is ended
Purpose: Verify the interaction of CAR_MANAGER and RIDE_MANAGER concerning RIDE/End
Dependencies: IT01C1 (concerning RIDE/Start) succeeded.

So che sono scemenze, ma temo che il prof valuti soprattutto quelle :(

**Comment by ZanSara** [comment]
Per ora lo faccio su un branch, poi dimmi che ne pensi

**Comment by siscia** [comment]
:+1: Sicuramente è più "proff. friendly"
