### ISSUE TITLE
IT02

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#68]
Perche' in IT01 a interagire sono solo GEOLOCATION e POSITION, mentre in IT02 anche CAR_MANAGER e' coinvolto?

**Comment by siscia** [comment]
Perchè serviva anche CAR/Teletry per identificare le macchine con qualche issues... Ti torna?

**Comment by ZanSara** [comment]
Ma allora anche in IT01 serve CAR_MANAGER, perche' CAR/Teletry fornisce anche la posizione... o ricordo male?

**Comment by siscia** [comment]
No POSITION fornisce la posizione...

**Comment by ZanSara** [comment]
Aaaaah si hai ragione :) Scusa ho fatto confusione
