### ISSUE TITLE
consistency check handled by DBMS

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#70]
Mi sono imbattuta in questo: _"Most of the consistency checks are handled by the DBMS itself."_ (valutazione di BOOKING).
Non dovremmo tener conto del tempo speso a inserire quei consistency checks nel database? Sono cosi automatici da richiedere poco tempo? Si potrebbe specificare.

**Comment by siscia** [comment]
Sto parlando di FOREIGN KEY check e condizioni minime tipo che la durata di un tratto deve essere maggiore di 0 secondi.

**Comment by ZanSara** [comment]
ok a posto :) Era solo per conferma
