### ISSUE TITLE
Frase che non mi torna in inglese

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#71]
Nella descrizione del Gantt:

_This approach is required since all the activities on each module should procede in parallel with developing and test well complected and the setting of the operational activity shortly after._

Sara' quasi mezzanotte e la stanchezza, ma non mi torna proprio l'inglese, non capisco cosa volevi scrivere 😅

**Comment by siscia** [comment]
Scusa, "complected" è un termine un pò particolare, significa "legate insieme", "fatte insieme"... Non sono sicuro sia inglese, comunque proviene da questo talk di Rick Hickey (il creatore di Clojure e altri meravigliosi pezzi di ingegneria): https://www.infoq.com/presentations/Simple-Made-Easy

Quello che intendevo è che si scrive test e codice insieme (o prima il test e poi il codice se segui TDD, o prima il codice e poi il test se non siamo religiosi) e insieme, ma anche un pò dopo, la parte di operation.

La parte di operation è quella che viene oggi anche chiamata DevOps, è quell'insieme di codice/script/configurazione che permette un facile (automatico) deploy.

**Comment by ZanSara** [comment]
Aaah ok, ora ho capito...

Non so se ci conviene tenerlo scritto cosi, perchè a maggior parte dei dizionari che ho visto riporta _complected_ come _di carnagione_, oppure come sinonimo di "having some complexion", dove _complexion_ significa "insieme dei tratti del volto e carnagione". Cioè, nella tua accezione può avere senso, ma è molto metaforico, al limite dell'improprio.

In ogni caso è un americanismo stretto (in british english nemmeno esiste questa parola) e temo che il prof, anche con tutta la buona volontà, non riuscirebbe a leggerlo nemmeno con il dizionario.
Te lo riscrivo, ok?

**Comment by siscia** [comment]
:+1:
