### ISSUE TITLE
Tempo di sviluppo stimato

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#72]
Nel capitolo 4 calcoli che il tempo stimato e' tra gli 8 e i 9 Person-Month.

Questo significa che, essendo in due, il tempo stimato e' di 4.5 mesi?

Se si, bisogna correggere una riga nel capitolo successivo dove specifichi che, aggiungendo due mesi, il tempo di sviluppo diventa di circa 11 mesi.

**Comment by siscia** [comment]
Si hai ragione!

Devo ricorreggere tutto il GANTT...

**Comment by siscia** [comment]
@ZanSara per piacere ricontrolla ora...

**Comment by ZanSara** [comment]
Ok mi sembra a posto ora :)
