### ISSUE TITLE
Function Points per la UI

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#73]
Mi sembra che manchino. Bisogna metterli? Ho visto che NOTIFY ha la sua stima, ma la UI in generale no.

**Comment by siscia** [comment]
Che la UI non è nei componenti...

Come hai visto poi gli ho abbozzati quando davo a te il lavoro...

Che dici?

**Comment by ZanSara** [comment]
Hai ragione... direi che ci sta anche così
