### ISSUE TITLE
Ri-renderizzare il DD

### ISSUE THREAD

**Issue by ZanSara** [siscia/INGSW2#74]
Ho trovato un BCE renderizzato male nel DD e l'ho ricommittato nuovo. Ho tentato di ricompilare il LaTeX ma, avendo dovuto cambiare pc (si. mi e' appena saltato il pc nuovo.) non riesco a ricompilarlo e mi da' errori di ogni tipo.

Quando hai un attimo ricompilalo, mettilo nei deliverables e pushalo, per favore...

**Comment by siscia** [comment]
Controlla che sia OK

Ho solo ripullato e compilato due volte...

Mi pare buono.

Cazzo sto computer!!!

**Comment by ZanSara** [comment]
Ok tutto a posto.
Non mettiamo niente nel changelog no?
